name: NodeJS with Webpack

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
    
    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Correct dir
      run: |
        cd assistantnms_web

    - name: Build
      run: |
        npm ci
        npm run build

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.0
      with:
        name: staticFiles
        path: ./**/*
      
    
